### PR TITLE
added support for zulu

### PR DESCRIPTION
**Pull request by ChaosKid42**
I would really like to see some report for zulu builds of openjdk. Therefore I'm submitting this PR.

### CODE REVIEW

**Comment by michaellass** [comment]
(Rebased onto recent master via force-push to fix the CI which was broken on master before)

Thanks for the pull request! I did not realize that the zulu packages in AUR use a different naming scheme. I would have expected java-${version}-zulu or something along those lines.

I am not entirely happy with how this would handle the zulu packages. I think they should be handled as a package variant similar to openjdk, adoptopenjdk, etc. (I.e., I would like to allow something like `--package zulu` to choose one of the zulu JREs.)

There are mainly two ways to achieve this:
1. Modify all the expressions to also account for `zulu(-embedded)?-${exp}` if no package was given or `zulu[-embedded]` was given as a package, or
2. do some pre- and post-processing on the list of available JREs to handle the `zulu(-embedded)?-${exp}` packages as `java-${exp}-zulu[-embedded]`

The first variant may become cumbersome as we always need to distinguish between no package given, zulu package given, zulu-embedded package given or any other package given.

I need to take a closer look on this before merging anything.

**Comment by michaellass** [comment]
I implemented a more general approach in 60ab2b7 which allows both naming schemes, java-$version-$package and $package-$version.

@ChaosKid42 could you please test the current version from master and report if it works for you?

**Comment by ChaosKid42** [comment]
> @ChaosKid42 could you please test the current version from master and report if it works for you?

@michaellass Works for me. Great. Thanks a lot!

**Comment by ChaosKid42** [comment]
@michaellass May I ask you to also update the corresponding AUR package? I'm actually using archlinux-java-run in https://aur.archlinux.org/packages/openhab3 and using zulu-java is advisable on embedded devices like the raspberry pi.

**Comment by michaellass** [comment]
Yes, I'm planning to release the changes soon. I'd like to go through a couple of tests before though. I hope to get it done by tomorrow.

**Comment by michaellass** [comment]
Sorry, it took a little longer. But the update (v9) is now release in the AUR.

**Comment by ChaosKid42** [comment]
Great to hear. Thanks!

**Comment by HappyRespawnanchor** [comment]
The issue seems to persist and was fixed in this PR. Why was this PR closed?

**Comment by michaellass** [comment]
>Why was this PR closed?

Because it was implemented in 60ab2b7ebfe457b8ae02c8e336013596bcfacab4. The java packages you are using have an entirely different naming scheme again. I moved your question into a separate issue (#10) and will respond over there soon.

**Pull request closed without merging**
